version: '3'

services:
  telegram-connector:
    container_name: telegram-connector
    restart: unless-stopped
    image: telegram-connector:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    env_file:
      - .env
    environment:
      - TZ=Europe/Kiev
      - APP_VERSION=${APP_VERSION:-dev}
    networks:
      - think-root-network

networks:
  think-root-network:
    external: true