version: '3'

services:
  telegram-connector:
    container_name: telegram-connector
    restart: always
    ports:
      - "127.0.0.1:${PORT:-8080}:${PORT:-8080}"
    image: telegram-connector:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=${APP_VERSION:-dev}
    env_file:
      - .env
    environment:
      - TZ=Europe/Kiev
      - APP_VERSION=${APP_VERSION:-dev}
      - PORT=${PORT:-8080}
    networks:
      - think-root-network

networks:
  think-root-network:
    external: true